CREATE TABLE NFRAME
(
  N_NUM NUMBER NOT NULL 
, N_TIT VARCHAR2(120) 
, N_CATE VARCHAR2(10) 
, N_CON CLOB 
, N_AUTHOR VARCHAR2(30) 
, N_DATE DATE 
, N_PIC VARCHAR2(50) 
, N_LINK VARCHAR2(60) 
, CONSTRAINT NFRAME_PK PRIMARY KEY 
  (
    N_NUM 
  )
  ENABLE 
);